const $=id=>document.getElementById(id);let state,latest=null,busy=false,abortSuite=false;
function notice(s){$('notice').textContent=s}
async function api(path,body){const r=await fetch(path,body?{method:'POST',headers:{'Content-Type':'application/json','X-Lab-Token':state.token},body:JSON.stringify(body)}:{});const d=await r.json();if(!r.ok)throw Error(d.error||r.statusText);return d}
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n}
function activate(name){document.querySelectorAll('.tab').forEach(n=>n.classList.toggle('hidden',n.id!==name));document.querySelectorAll('nav button').forEach(n=>n.classList.toggle('active',n.dataset.tab===name))}
function customFixture(){return $('goal').value==='custom'?JSON.parse($('custom-fixture').value):undefined}
$('goal').onchange=()=>{$('custom-panel').classList.toggle('hidden',$('goal').value!=='custom')};
function renderFlow(){const box=$('recipe-view');box.replaceChildren();try{const p=JSON.parse($('proposal').value);for(const s of p.recipe.steps)box.append(el('span',s.id+' · '+s.op,'node'))}catch{}}
async function refresh(){state=await api('/api/state');$('mode').textContent=state.stopped?'Stopped':'Ready · local only';$('stop').textContent=state.stopped?'Resume experiments':'Stop experiments';renderAssembly();$('tool-count').textContent=state.tools.length;$('run-count').textContent=state.runs.length;
 $('tools').replaceChildren();for(const t of state.tools){const n=el('div',undefined,'record');n.append(el('strong',t.name),el('p','Verified: '+t.verified_scope.goal+' / '+t.verified_scope.condition+' · source: '+t.origin_source,'small'));const use=el('button','Compose with this tool');use.onclick=()=>{const proposal={participant:'Name your AI or author',missing_function:'Use and extend a previously resolved method',prediction:'State the behavior expected for the selected goal',dependency:'use_tool',recipe:{steps:[{id:'reused',op:'use_tool',inputs:['$left','$right'],params:{tool_id:t.id}}],output:'reused'}};$('proposal').value=JSON.stringify(proposal,null,2);$('source').value='authored_demo';renderFlow();activate('workbench');notice('Tool recipe loaded. Set the participant, prediction and goal before running.')};n.append(use);$('tools').append(n)}if(!state.tools.length)$('tools').append(el('p','No created tools yet. Promote a passing run.','muted'));
 for(const id of ['pair-a','pair-b']){const box=$(id);box.replaceChildren();for(const r of state.runs){const o=el('option',r.condition+' / '+r.goal+' · '+r.id.slice(0,8));o.value=r.id;box.append(o)}}if(state.runs.length)$('pair-b').value=state.runs.at(-1).id;
 $('runs').replaceChildren();for(const r of [...state.runs].reverse()){const n=el('div',undefined,'record');n.append(el('strong',(r.passed?'PASS':'NOT RESOLVED')+' · '+r.proposal.participant,r.passed?'passed':'failed'),el('p',r.condition+' / '+r.goal+' · '+r.source+' · '+r.utc,'small'));const view=el('button','Inspect receipt');view.onclick=()=>{latest=r;showResult(r);activate('workbench');$('result').scrollIntoView({behavior:'smooth'})};const download=el('button','Download JSON');download.onclick=()=>saveJSON(r,'emergence-'+r.id+'.json');n.append(view,download);$('runs').append(n)}}
$('compare-pair').onclick=async()=>{try{const r=await api('/api/compare',{previous:$('pair-a').value,current:$('pair-b').value});$('pair-result').textContent=JSON.stringify(r,null,2);notice('Paired evidence evaluated. Authorship and causal interpretation remain explicit.')}catch(e){notice(e.message)}};
function saveJSON(data,name){const u=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=el('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function showResult(r){const box=$('result');box.replaceChildren(el('span','AUDIENCE · REALITY RETURN','eyebrow'),el('h2',r.passed?'Behavior resolved on this fixture':'Prediction not resolved',r.passed?'passed':'failed'),el('p',r.proposal.participant+' · '+r.source+' · '+r.condition,'small'));if(r.error)box.append(el('p',r.error,'failed'));const grid=el('div',undefined,'result-grid');for(const [label,value] of [['Observed output',r.output],['Evaluator target',r.expected]]){const cell=el('div');cell.append(el('strong',label),el('pre',JSON.stringify(value,null,2)));grid.append(cell)}box.append(grid);const details=el('details');details.append(el('summary','Execution trace · '+r.trace.length+' records'),el('pre',JSON.stringify(r.trace,null,2)));box.append(details,el('p','Recipe '+r.recipe_sha256+' · receipt '+r.receipt_sha256,'small'),el('p',r.evaluation,'muted'));const actions=el('div',undefined,'actions');const exportBtn=el('button','Download receipt');exportBtn.onclick=()=>saveJSON(r,'emergence-'+r.id+'.json');actions.append(exportBtn);if(r.passed){const name=el('input');name.placeholder='Name the created tool';name.setAttribute('aria-label','Created tool name');const promote=el('button','Keep as reusable tool');promote.onclick=async()=>{try{await api('/api/promote',{run_id:r.id,name:name.value});await refresh();notice('Saved immutable tool. It is now an ingredient in the library.')}catch(e){notice(e.message)}};box.append(name);actions.append(promote)}box.append(actions)}
async function run(suite){if(busy)return;busy=true;abortSuite=false;$('run').disabled=$('suite').disabled=true;try{const proposal=JSON.parse($('proposal').value);if(suite&&$('goal').value==='custom')throw Error('Custom fixtures run one selected condition at a time. Change your inputs explicitly for paired tests.');const conditions=suite?['baseline','noise','schema','holdout']:[$('condition').value];let pass=0;for(const condition of conditions){if(abortSuite)break;const r=await api('/api/run',{proposal,source:$('source').value,goal:$('goal').value,condition,custom_fixture:customFixture(),disabled:$('disabled').value,parent_run:latest?.id||null});latest=r;showResult(r);if(r.passed)pass++}await refresh();notice(suite?`${pass} of ${conditions.length} fixtures passed. These are repeated recipe executions, not independent AI trials.`:'Saved attributed experiment receipt.')}catch(e){notice(e.message)}finally{busy=false;$('run').disabled=$('suite').disabled=false}}
document.querySelectorAll('nav button').forEach(n=>n.onclick=()=>activate(n.dataset.tab));$('proposal').addEventListener('input',renderFlow);$('run').onclick=()=>run(false);$('suite').onclick=()=>run(true);
$('demo').onclick=()=>{$('proposal').value=JSON.stringify(state.demo,null,2);$('source').value='authored_demo';renderFlow();notice('Authored example loaded. No AI inference was performed.')};
$('stop').onclick=async()=>{try{abortSuite=true;await api(state.stopped?'/api/resume':'/api/stop',{});await refresh();notice(state.stopped?'Stopped. No new experiment runs are accepted; completed receipts remain available.':'Explicitly resumed.')}catch(e){notice(e.message)}};
$('packet').onclick=async()=>{try{const p=await api('/api/packet',{goal:$('goal').value,condition:$('condition').value,custom_fixture:customFixture()});$('packet-text').value=JSON.stringify(p,null,2);$('packet-panel').classList.remove('hidden');$('packet-panel').scrollIntoView({behavior:'smooth'});notice('Packet prepared. No message sent and no model called.')}catch(e){notice(e.message)}};
$('copy-packet').onclick=async()=>{try{await navigator.clipboard.writeText($('packet-text').value);notice('Packet copied.')}catch{$('packet-text').focus();$('packet-text').select();notice('Packet selected. Press Ctrl+C to copy.')}};
refresh().then(()=>{for(const [name,description] of Object.entries(state.primitives)){const n=el('div',undefined,'ingredient');n.append(el('strong',name),el('p',description));$('primitives').append(n);const opt=el('option',name);opt.value=name;$('disabled').append(opt)}$('disabled').value='normalize'}).catch(e=>notice('Could not connect: '+e.message));

let chosen=new Set(),edges=[];
function renderAssembly(){
 const box=$('pieces');box.replaceChildren();
 for(const p of state.pieces){const label=el('label',undefined,'record');const check=el('input');check.type='checkbox';check.checked=chosen.has(p.id);check.onchange=()=>{if(check.checked)chosen.add(p.id);else{chosen.delete(p.id);edges=edges.filter(e=>e.from!==p.id&&e.to!==p.id)}renderEdges()};label.append(check,el('strong',p.name+' · '+p.type),el('p',p.function),el('small',p.scope));box.append(label)}
 renderEdges();$('creations').replaceChildren();
 for(const c of [...state.creations].reverse()){const n=el('div',undefined,'record');n.append(el('h3',c.title),el('p',c.participant+' · created artifact · claims unverified'),el('pre',c.artifact));const details=el('details');details.append(el('summary','Assembly, governance and claims'),el('pre',JSON.stringify(c,null,2)));n.append(details);const download=el('button','Download creation');download.onclick=()=>saveJSON(c,'creation-'+c.id+'.json');const test=el('button','Take claims to test workbench');test.onclick=()=>{activate('workbench');$('goal').value='custom';$('custom-panel').classList.remove('hidden');$('custom-fixture').value=JSON.stringify({goal:'Source creation '+c.id+': '+c.function+' Claims: '+c.claims.join('; '),left:{},right:{},expected:null},null,2);notice('Define independent inputs and expected output, then supply an executable proposal. Source creation: '+c.id)};n.append(download,test);$('creations').append(n)}
}
function renderEdges(){
 for(const id of ['edge-from','edge-to']){const box=$(id),value=box.value;box.replaceChildren();for(const p of state.pieces.filter(x=>chosen.has(x.id))){const o=el('option',p.name);o.value=p.id;box.append(o)}if(chosen.has(value))box.value=value}
 $('edges').replaceChildren();for(const [i,e] of edges.entries()){const n=el('div',e.from+' → '+e.relation+' → '+e.to,'record');const b=el('button','Remove');b.onclick=()=>{edges.splice(i,1);renderEdges()};n.append(b);$('edges').append(n)}
}
$('edge-add').onclick=()=>{const from=$('edge-from').value,to=$('edge-to').value;if(!from||!to)return notice('Select pieces first.');edges.push({from,to,relation:$('edge-kind').value});renderEdges()};
for(const t of ['concept','lens','method','context','rule','memory','capability','creation']){const o=el('option',t);o.value=t;$('piece-type').append(o)}
$('piece-save').onclick=async()=>{try{const p={type:$('piece-type').value};for(const k of ['name','function','content','scope','provenance'])p[k]=$('piece-'+k).value;await api('/api/assembly/piece',p);await refresh();notice('Functional piece saved.')}catch(e){notice(e.message)}};
$('assemble').onclick=async()=>{try{const packet=await api('/api/assembly/assemble',{goal:$('assembly-goal').value,pieces:[...chosen],relationships:edges,configuration:$('assembly-config').value,starting_state:$('assembly-start').value,environment:$('assembly-env').value});$('packet-text').value=JSON.stringify(packet,null,2);$('creation-json').value=JSON.stringify(packet.reply_contract,null,2);$('packet-panel').classList.remove('hidden');$('packet-panel').scrollIntoView();await refresh();notice('Assembly saved. Copy the packet to your synthesis conversation and return its reply.')}catch(e){notice(e.message)}};
$('creation-save').onclick=async()=>{try{await api('/api/assembly/creation',JSON.parse($('creation-json').value));await refresh();notice('Creation saved with lineage. Available as an ingredient; claims remain unverified.')}catch(e){notice(e.message)}};

